ignored:
  - DL3008  # Pin versions in apt get install (sometimes not needed in development)
  - DL3009  # Delete the apt-get lists after installing something
  - DL3015  # Avoid additional packages by specifying `--no-install-recommends`

# Override default rules
override:
  error:
    - DL3020  # Use COPY instead of ADD for files and folders
    - DL3025  # Use arguments JSON notation for CMD and ENTRYPOINT arguments
  warning:
    - DL3018  # Pin versions in apk add
    - DL3019  # Use the `--no-cache` switch to avoid the need to use `--update` and remove `/var/cache/apk/*`
  info:
    - DL3032  # `yum clean all` missing after `yum` command
    - DL3033  # Specify version with `yum install -y <package>-<version>`

# Trusted registries for base images
trustedRegistries:
  - docker.io
  - gcr.io
  - quay.io
