# 🚀 Configuración Dokploy/Nixpacks para Frontend DELA
# ✅ Optimizada para Next.js 15 con Tailwind CSS v4

[setup]
nixpkgs = ["nodejs_18", "npm", "python3", "gcc", "gnumake"]

[install]
cmd = "npm ci --prefer-offline --no-audit"

[build]
cmd = "npm run build"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "3000"
HOSTNAME = "0.0.0.0"
NPM_CONFIG_CACHE = ".npm"

# 📦 Cache para optimizar builds
[staticAssets]
"public" = "./public"
".next/static" = "./.next/static"
