# 🚀 Configuración Dokploy/Nixpacks para Frontend DELA
# ✅ Optimizada para Next.js 15 con Tailwind CSS v4

[phases.setup]
nixPkgs = ["nodejs_18", "npm-8_x", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "3000"
HOSTNAME = "0.0.0.0"
